### ISSUE TITLE
Missing com.thoughtworks.go:go-plugin-api:15.1.0 article

### ISSUE THREAD

**Issue by mingfang** [gocd/go-plugins#10]
I'm unable to build this project due to missing articles.
It looks like they are not in Maven Central.
Can you either upload to Maven Central or give us access to your repo?

**Comment by decoomanj** [comment]
Yes, this is a known issue. Currently the JAR *go-plugin-api-14.3.0.jar* is missing. It's not in the repos. But, you can find it in your go-server installation-directory as a workaround. Go to your-go-server-14.3.0/plugins_work/docker-material-poller-0.0.1.jar/lib and look for the file there. You can install it then with maven in your local repo. 

The Go-team is aware of this issue and they wanted to fix it. I will change my POM when the file is available.

**Comment by arvindsv** [comment]
Sorry, closed by mistake. [14.4.0](http://search.maven.org/#artifactdetails%7Ccd.go.plugin%7Cgo-plugin-api%7C14.4.0%7Cpom) is up on Maven Central. I started again today, to push every revision up to Maven Central, automatically from build.go.cd. I'll finish it tomorrow.

**Comment by arvindsv** [comment]
This is done. See https://github.com/gocd/gocd/issues/139.
