### ISSUE TITLE
Sample authentication plugin is broken in latest 15.3

### ISSUE THREAD

**Issue by pshelton-skype** [gocd/go-plugins#28]
The sample authentication plugin works as intended when run against the 15.2.0 tag in the gocd repository, but updating to the latest commit to master (pre-release 15.3) causes a 404 to occur anytime the plugin icon is clicked, breaking the authentication flow, as demonstrated below.

#### 15.2:
![15 2](https://cloud.githubusercontent.com/assets/8740771/10259214/8e45c9e8-691a-11e5-8c4e-1545d7d4c6c2.gif)

#### 15.3:
![15 3](https://cloud.githubusercontent.com/assets/8740771/10259236/db23d61a-691a-11e5-9c45-49cb05dae67b.gif)

The developer documentation hasn't been updated to indicate what change is required to the authentication plugins to make them work in 15.3 and there are no bugs related to the authentication flow on the main gocd project, but I can't determine whether this is API breaking change, a bug in Go, or a bug in the plugin.

**Comment by pshelton-skype** [comment]
Possibly related to https://github.com/gocd/gocd/commit/764eb289baf4183cf597c5afa0ea553da8c8283a?

**Comment by zabil** [comment]
@pshelton-skype that's the fix to this problem. Can you tell us which revision you are at?

**Comment by zabil** [comment]
I've verified that it works on gocd/master revision ad8fc27d552f038fc8609c27cd0d6e4eadd90739

**Comment by pshelton-skype** [comment]
Oh, weird. I managed to clone the main gocd repository from Aug 19 rather than latest somehow. Thanks for the verification.
